const MOCK_PHOTOS_COUNT = 25;

const MAX_MOCK_COMMENTS_COUNT = 30;

const MIN_MOCK_LIKES_COUNT = 15;
const MAX_MOCK_LIKES_COUNT = 200;

const COMMENT_ID_START_FROM = 135;

export {
  COMMENT_ID_START_FROM, MAX_MOCK_COMMENTS_COUNT, MAX_MOCK_LIKES_COUNT, MIN_MOCK_LIKES_COUNT, MOCK_PHOTOS_COUNT
};

